---
- name: 'Update and upgrade apt packages'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: 'Install packages'
  become: yes
  apt:
    pkg:
      - python3-pip
      - git
      - vim
      - zsh
      - tmux
- pip:
    name: glances
    executable: pip3
- name: 'clone oh-my-zsh for users'
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~{{ ansible_user_id }}'
    creates: '~{{ ansible_user_id }}/.oh-my-zsh'
- name: 'set permissions of oh-my-zsh for users'
  become: yes
  file:
    path: '~{{ ansible_user_id }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: yes
- name: 'set default shell for users'
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh
- name: 'write .zshrc for users'
  become: yes
  template:
    src: zshrc.j2
    dest: '~{{ ansible_user_id }}/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'