---
- name: Creating RPi exporter user group
  become: yes
  group: name="{{groupId}}"

- name: Creating RPi exporter user
  become: yes
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present


- name: Install RPi Exporter
  unarchive:
    src: "https://github.com/lukasmalkmus/rpi_exporter/releases/download/v{{version}}/rpi_exporter-{{version}}.linux-arm64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy RPi Exporter file to bin
  become: yes
  copy:
    src: "/tmp/rpi_exporter-{{version}}.linux-arm64/rpi_exporter"
    dest: "/usr/local/bin/rpi_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete RPi Exporter tmp folder
  file:
    path: '/tmp/rpi_exporter-{{version}}.linux-arm64/rpi_exporter'
    state: absent

- name: Copy systemd init file
  become: yes
  template:
    src: rpi_exporter.service.j2
    dest: /etc/systemd/system/rpi_exporter.service
  notify: systemd_reload

- name: Start RPi Exporter service
  become: yes
  service:
    name: rpi_exporter 
    state: started
    enabled: yes

- name: Check if RPi exporter emits metrices
  uri:
    url: http://127.0.0.1:9243/metrics
    method: GET
    status_code: 200
